[2024-07-15 17:41:18,258] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8000
 * Running on http://192.168.29.35:8000
[2024-07-15 17:41:18,259] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2024-07-15 17:41:26,221] 97 werkzeug - INFO - 127.0.0.1 - - [15/Jul/2024 17:41:26] "GET / HTTP/1.1" 200 -
[2024-07-15 17:41:26,461] 97 werkzeug - INFO - 127.0.0.1 - - [15/Jul/2024 17:41:26] "GET / HTTP/1.1" 200 -
[2024-07-15 17:41:45,545] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:41:45] "GET / HTTP/1.1" 200 -
[2024-07-15 17:41:45,587] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:41:45] "GET / HTTP/1.1" 200 -
[2024-07-15 17:42:25,592] 1414 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 16, in predict_datapoint
    return render_template("form.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: form.html
[2024-07-15 17:42:25,598] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:25] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
[2024-07-15 17:42:25,636] 1414 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 16, in predict_datapoint
    return render_template("form.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: form.html
[2024-07-15 17:42:25,639] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:25] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
[2024-07-15 17:42:33,564] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:33] "[33mGET /predict.html HTTP/1.1[0m" 404 -
[2024-07-15 17:42:33,594] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:33] "[33mGET /predict.html HTTP/1.1[0m" 404 -
[2024-07-15 17:42:36,554] 1414 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 16, in predict_datapoint
    return render_template("form.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: form.html
[2024-07-15 17:42:36,556] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:36] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
[2024-07-15 17:42:49,866] 1414 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 16, in predict_datapoint
    return render_template("form.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: form.html
[2024-07-15 17:42:49,868] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:49] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
[2024-07-15 17:42:49,897] 1414 app - ERROR - Exception on /predict [GET]
Traceback (most recent call last):
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "app.py", line 16, in predict_datapoint
    return render_template("form.html")
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 150, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1084, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 1013, in get_template
    return self._load_template(name, globals)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 64, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\salvi\anaconda3\envs\emp\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: form.html
[2024-07-15 17:42:49,898] 97 werkzeug - INFO - 192.168.29.35 - - [15/Jul/2024 17:42:49] "[35m[1mGET /predict HTTP/1.1[0m" 500 -
